const server = [
    {
        path:"/view",
        route:"./routes/view"
    },
    {
        path:"/user",
        route:"./routes/user"
    },
    {
        path:"/menu",
        route:"./routes/menu"
    },
    {
        path:"/grade",
        route:"./routes/grade"
    },
    {
        path:"/course",
        route:"./routes/course"
    },
    {
        path:"/work",
        route:"./routes/work"
    },
    {
        path:"/scoure",
        route:"./routes/scoure"
    }
];
module.exports = server;